
urlhead = 'http://www.exposomex.cn:8080/'

#' @title Initialize HExpPridict module
#' @description Initialize HExpPridict module analysis. It can generate an R6 class object
#'     integrating all the analysis information.
#' @usage InitHEP()
#' @param
#' @details ExpoHExpPredict module is designed  to predict blood concentrations of
#'     chemicals and prioritize chemicals of health concern.
#' @return An R6 class object.
#' @export
#' @examples res <- InitHEP()
#' @author Mingliang Fang, Bin Wang,(corresponding author)


InitHEP = function(){
  url = paste0(urlhead,'InitHEP')
  seednum = sample(1000,1)
  res = httr::POST(url,
                   body = list(seednum=seednum),
                   encode = 'json')
  results = unserialize(httr::content(res))
  return(results$eSet)
}


#' @title Load data file for HExpPridict module
#' @description Load data file for HExpPridict module.
#' @usage LoadHEP(PID, UseExample = "default", DataPath=NULL)
#' @param PID chr. Program ID. It must be the same with the PID generated by InitHEP.
#' @param UseExample chr. Method of uploading data. If "default",user should upload their own data files,
#'    or use "example#1" provided by this module.
#' @param DataPath chr. Input file directory, e.g. "D:/test/eg_hep.xlsx". It should be
#'    noted that the slash symbol is "/", not "\".
#' @details
#' @return An R6 class object containing the input data.
#' @export
#' @examples res <- InitHEP()
#'    res = LoadHEP(PID = res$PID, UseExample = "example#1")
#' @author Mingliang Fang, Bin Wang (corresponding author)

LoadHEP =function(PID,
                      UseExample = "default",
                      DataPath = NULL){
  url = paste0(urlhead,'LoadHEP')
  if(UseExample=="default"){
    exdata = readxl::read_excel(DataPath)
  }else{
    exdata = NULL}
  res = httr::POST(url,
                   body = serialize(list(PID=PID,
                                         UseExample=UseExample,
                                         Expodata=exdata),connection = NULL),
                   httr::content_type('application/x-rds'),
                   encode = 'raw')
  results = unserialize(httr::content(res))
  # results list
  return(results$eSet)
}


#' @title Convert different IDs to the unified ExposomeX IDs
#' @description Convert the IDs of exposure, chemicals, metabolites, or proteins to the unified ExposomeX ID,
#'     i.e., unified identifier in ExposomeX platform
#' @usage ConvToExpoID(PID,OutPath="default")
#' @param PID chr. Program ID. It must be the same with the PID generated by InitHEP.
#' @param OutPath chr. Output file directory, e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @details
#' @return A data frame containing the converted ID information.
#' @export
#' @examples res = InitHEP()
#'    res1 = LoadHEP(PID = res$PID,UseExample = "example#1")
#'    res2 = ConvToExpoID(PID = res$PID)
#' @author Mingliang Fang, Weinan Lin, Bin Wang (corresponding author)

ConvToExpoID = function(PID,
                        OutPath="default"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'ConvToExpoID')
  res = httr::POST(url,
                   body = list(PID=PID),
                   encode = 'json')
  results = unserialize(httr::content(res))

  dir.create(paste0(OutPath,'/ConvToExpoID'))

  try(vroom::vroom_write(results$Data,paste0(OutPath,"/ConvToExpoID/ExpoData.csv"),
                         delim = ","),silent = TRUE
  )
  return(results$Data)
}


#' @title Predict blood concentrations of chemicals
#' @description Predict blood concentrations of chemicals
#' @usage PredBlood(PID, OutPath="default",MC = "F",N=100)
#' @param PID chr. Program ID. It must be the same with the PID generated by InitHEP.
#' @param OutPath chr. Output file directory. e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param MC lgl. T (or TRUE) and F (or FALSE). Whether to perform Mentocaro simulation.
#' @param N num. Times of Mentocaro simulation.
#' @details
#' @return A list object containing the prediction results.
#' @export
#' @examples res = InitHEP()
#'    res1 = LoadHEP(PID = res$PID,UseExample = "example#1")
#'    res2 = ConvToExpoID(PID = res$PID)
#'    res3 = PredBlood(PID = res$PID, OutPath="default", MC ='F',N=1000)
#' @author Mingliang Fang, Bin Wang (corresponding author)

PredBlood = function(PID,
                   OutPath="default",
                   MC = "F",
                   N = 1000
){
  if(OutPath == "default"){
    OutPath = getwd()
  }

  message("It may take some time. Thanks for your patient waiting!")

  url = paste0(urlhead,'PredBlood')
  res = httr::POST(url,
                   body = list(PID=PID,
                               MC=MC,
                               N=N
                   ),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,'/PredBlood'))
  try(writexl::write_xlsx(results$PredBlood$model_fit_rf_parameters,paste0(OutPath,"/PredBlood/model_fit_rf_parameters.xlsx")),silent = TRUE
  )
  try(writexl::write_xlsx(results$PredBlood$model_fit_vars_imp,paste0(OutPath,"/PredBlood/model_fit_vars_imp.xlsx")),silent = TRUE
  )
  try(writexl::write_xlsx(results$PredBlood$model_fit_summary,paste0(OutPath,"/PredBlood/model_fit_summary.xlsx")),silent = TRUE
  )
  try(writexl::write_xlsx(results$PredBlood$model_fit_data,paste0(OutPath,"/PredBlood/model_fit_data.xlsx")),silent = TRUE
  )
  try(writexl::write_xlsx(results$PredBlood$model_formulae,paste0(OutPath,"/PredBlood/model_formulae.xlsx")),silent = TRUE
  )
  try(writexl::write_xlsx(results$PredBlood$model_cv_summary,paste0(OutPath,"/PredBlood/model_cv_summary.xlsx")),silent = TRUE
  )
  try(writexl::write_xlsx(results$PredBlood$pred_Cb,paste0(OutPath,"/PredBlood/pred_Cb.xlsx")),silent = TRUE
  )

  ggplot2::ggsave(paste0(OutPath, "/PredBlood/plot_model_fit.png"),
           plot = results$PredBlood$plot_model_fit,
           dpi = 600)
  return(results)
}



#' @title Visualize the PredBlood
#' @description Visualize the PredBlood.
#' @usage VizPredBlood(PID,OutPath="default",Layout="forest",
#'     Brightness="light",Palette= "science")
#'
#' @param PID chr. Program ID. It must be the same with the PID generated by InitBioLink.
#' @param OutPath chr. Output file directory. e.g. "D:/test". It should be noted that the slash symbol is "/", not "\".
#'     If "default", the current working directory will be set.
#' @param Layout chr. Visualization layout. Available options include "forest" and "boxplot".
#' @param Brightness chr. Visualization brightness. Available options include "light" and "dark".
#' @param Palette chr. Visualization palette. Available options include "default1", "default2"
#'    and several journal preference styles (i.e., cell, nature, science, lancet, nejm, and jama).
#' @details
#' @return A list object containing the plot of the biological link. This plot can be further processed using ggplot2 package.
#' @export
#' @examples res = InitHEP()
#'    res1 = LoadHEP(PID = res$PID,UseExample = "example#1")
#'    res2 = ConvToExpoID(PID = res$PID)
#'    res3 = PredBlood(PID = res$PID, OutPath="default", MC ='F', N=1000)
#'    res4 = VizPredBlood(PID = res$PID, OutPath ="default",Layout="forest",
#'    Brightness="light",Palette= "science" )
#' @author Mingliang Fang, Ning Gao, Bin Wang (corresponding author)

VizPredBlood = function(PID,
                      OutPath="default",
                      Layout = "forest",
                      Brightness = "light",
                      Palette = "default1"){
  if(OutPath == "default"){
    OutPath = getwd()
  }
  url = paste0(urlhead,'VizPredBlood')
  res = httr::POST(url,
                   body = list(PID=PID,
                               Layout=Layout,
                               Brightness =Brightness,
                               Palette = Palette),
                   encode = 'json')
  results = unserialize(httr::content(res))

  dir.create(paste0(OutPath,'/VizPredBlood'))

  ggplot2::ggsave(paste0(OutPath,'/VizPredBlood/plot_pred.png'),
                  plot = results$VizPredBlood$plot_pred,
                  dpi = 600)

  try(ggplot2::ggsave(paste0(OutPath,'/VizPredBlood/',Layout,"_",Brightness,"_",Palette,".png"),
                    plot = results$VizPredBlood$ForestPlot[[paste0(Brightness,"_",Palette)]],
                    width = 15,
                    height =  results$VizPredBlood$ForestPlot_para[['PlotHeight']],
                    units = "cm",dpi = 300,
                    limitsize = FALSE),silent = TRUE
  )

  try(ggplot2::ggsave(paste0(OutPath,'/VizPredBlood/box_plot.png'),
                    plot = results$VizPredBlood$BoxPlot,
                    width = results$VizPredBlood$BoxPlot_para[['PlotWidth']],
                    height = 15,
                    units = "cm",dpi = 300,
                    limitsize = FALSE),silent = TRUE
  )

  return(results)
}


#' @title End the module analysis
#' @description End the module analysis
#' @usage FuncExit(PID)
#' @param PID chr. Program ID. It must be the same with the PID generated by any initial functions.
#' @details
#' @return Exit status
#' @export
#' @examples res = InitHEP()
#'    res = LoadHEP(PID = res$PID,UseExample = "example#1")
#'    FuncExit(PID = res$PID)
#' @author Bin Wang (corresponding author)

FuncExit = function(PID){
  url = paste0(urlhead,'Exit')
  res = httr::POST(url,
                   body = list(PID=PID),
                   encode = 'json')
  if(res$status_code == 200){
    return("Success to exit. Thanks for using ExposomeX platform!")
  }else{
    return("No process needs exit. Thanks for using ExposomeX platform!")
  }
}

